version: "3.8"
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=arquitectura
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    depends_on:
      - rabbitmq_cloud

  rabbitmq_cloud:
    image: rabbitmq:3-management
    container_name: rabbitmq_cloud
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  sign:
    image: sign/cloud
    build: ./sign
    container_name: sign-cloud
    environment:
      - DB_HOST=postgres_db
      - AUTH_HOST=authorization-server
    depends_on:
      - postgres_db

  manage-conversion:
    image: manage-conversion/cloud
    container_name: manage-conversion
    build: ./manage-conversion
    environment:
      - DB_HOST=postgres_db
      - BROKER_HOST=rabbitmq_cloud
    depends_on:
      - postgres_db
      - rabbitmq_cloud

  convert-video:
    image: convert-video/cloud
    container_name: convert-video
    build: ./convert-video
    environment:
      - DB_HOST=postgres_db
      - BROKER_HOST=rabbitmq_cloud
    depends_on:
      - postgres_db
      - rabbitmq_cloud

  authorization-server:
    image: authorization-server/cloud
    build: ./authorization-server
    container_name: authorization-server

  gateway:
    image: gateway/cloud
    build: ./gateway
    container_name: gateway-cloud
    ports:
    - "5000:5000"
    environment:
      - AUTH_HOST=authorization-server
      - SIGNUP_HOST=sign
      - LOGIN_HOST=sign
      - INIT_CONVERSION_HOST=manage-conversion
      - MANAGE_CONVERSION_HOST=manage-conversion
      - LIST_TASKS_HOST=manage-conversion
      - DELETE_TASK_HOST=manage-conversion

volumes:
  pg-data:
